# Generated by Django 5.1.4 on 2025-01-26 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_leyenda_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('historia', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_autor', to=settings.AUTH_USER_MODEL)),
                ('autor_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
