# Generated by Django 5.1.4 on 2025-01-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_album_autor_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='autor_album',
            field=models.CharField(max_length=100),
        ),
    ]
